# Generated by Django 3.2.4 on 2021-06-21 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slag',
            new_name='slug',
        ),
    ]
