# Generated by Django 3.2.4 on 2021-07-21 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_slag_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'verbose_name': 'ПРОДУКТ', 'verbose_name_plural': 'ПРОДУКТЫ'},
        ),
    ]
