# Generated by Django 3.2.4 on 2021-07-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_stock',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
